// <auto-generated />
using System;
using EmpresasIntegration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmpresasIntegration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116204730_AddJsonAndCnpjNormalized")]
    partial class AddJsonAndCnpjNormalized
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmpresasIntegration.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Abertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("abertura");

                    b.Property<string>("AtividadePrincipalJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("atividade_principal");

                    b.Property<string>("AtividadesSecundariasJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("atividades_secundarias");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("BillingJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("billing");

                    b.Property<decimal?>("CapitalSocial")
                        .HasColumnType("numeric")
                        .HasColumnName("capital_social");

                    b.Property<string>("Cep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cep");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CnpjNormalized")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj_normalized");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataSituacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_situacao");

                    b.Property<DateTime?>("DataSituacaoEspecial")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_situacao_especial");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra");

                    b.Property<string>("Fantasia")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("fantasia");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("logradouro");

                    b.Property<string>("MotivoSituacao")
                        .HasColumnType("text")
                        .HasColumnName("motivo_situacao");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("NaturezaJuridica")
                        .HasColumnType("text")
                        .HasColumnName("natureza_juridica");

                    b.Property<string>("Nome")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Porte")
                        .HasColumnType("text")
                        .HasColumnName("porte");

                    b.Property<string>("QsaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("qsa");

                    b.Property<string>("SimeiJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("simei");

                    b.Property<string>("SimplesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("simples");

                    b.Property<string>("Situacao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("situacao");

                    b.Property<string>("SituacaoEspecial")
                        .HasColumnType("text")
                        .HasColumnName("situacao_especial");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("telefone");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasMaxLength(50)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_atualizacao");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("CnpjNormalized")
                        .HasDatabaseName("IX_empresas_cnpj_normalized");

                    b.ToTable("empresas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
